### ISSUE TITLE
Wrong arrow location when content is Chinese

### ISSUE THREAD

**Issue by cces1004406** [Guad/NativeUI#111] opened 2019-06-19 18:48 UTC
![image](https://user-images.githubusercontent.com/14952501/59791745-5adc0900-9305-11e9-841d-d69ebac318b7.png)

**Comment by justalemon** [comment] 2019-06-20 02:13
Looks like this is related to #74.

This is a general problem with characters outside of the English Alphabet (like Ñ, 同, 左)

**Comment by justalemon** [comment] 2019-08-25 22:27
At the end, this is not related to #74 or #71, but the cause is similar: we are not calculating the width correctly.

**Comment by justalemon** [comment] 2019-08-25 22:35
@cces1004406 If possible, can you post the string on the arrows that has the problem?

**Comment by cces1004406** [comment] 2019-08-25 23:45
左前門

**Comment by justalemon** [comment] 2019-08-25 23:55
So I've been working on a patch for the last 5 hours, and I have tried the following as items:

* グランド・セフト・オートV (`Grand Theft Auto V` in Japanese)
* 俠盜獵車手V (`Grand Theft Auto V` in Chinese)
* 左前門 (Posted by @cces1004406 )

And so far it works:

![image](https://user-images.githubusercontent.com/11861253/63657613-05dbc980-c772-11e9-85de-e10a5494ef46.png)
![image](https://user-images.githubusercontent.com/11861253/63657615-0d9b6e00-c772-11e9-815e-76b1c76f51a4.png)

So I'm closing because it appears that has been fixed, let me know if you find other bugs.

**Closed by justalemon** 2019-08-25 23:55 UTC
Labels: bug, help wanted
