### ISSUE TITLE
Colour control characters causing bias in string width evaluation.

### ISSUE THREAD

**Issue by LeeC2202** [Guad/NativeUI#71] opened 2017-09-03 21:00 UTC
If you have the strings "This is a yellow string" and "This is a ~y~yellow string", the width is being evaluated taking into account the colour control characters. The consequence of this is text wrapping when there is sufficient space left to display the wrapped words.

To see an example of this, create a UIMenuItem with the following properties.

```cs
new UIMenuItem("Some text", "~w~Type: ~y~Off-Road, ~w~Difficulty: ~y~Professional")
```

and another with these

```cs
new UIMenuItem("Some text", "Type: ~y~Off-Road, ~w~Difficulty: ~y~Professional")
```

Even though the visible textual content is identical, the top one will force the word Professional onto the second line, whereas the second one will leave everything on one line. The second one is fine if you want the first word to be white but it fails if you don't.

Ideally, upon creation of any menu item subtitle, the string needs to be passed through a control code removal function before being passed to the string width checking and then the width of that processed string storing as a value in the class. That way, the only additional processing that occurs is at creation time, which won't impact on performance... plus you get accurately wrapped coloured strings. There is an ideal Dictionary based solution on this page: https://stackoverflow.com/questions/1321331/replace-multiple-string-elements-in-c-sharp

You can see an example of how this affects presentation in this image. The amount of space in the top box makes it look really bad.

![text-wrapping](https://user-images.githubusercontent.com/13275001/30006566-e9bb0584-90f2-11e7-98f7-f070b5f263a2.jpg)

**Comment by Guad** [comment] 2017-09-03 22:24
Ideally you'd use game's text measuring system with 0x9040DFB09BE75706 to get the text's line count.

**Comment by LeeC2202** [comment] 2017-09-03 22:32
I have no control over the measuring, that's being done by NativeUI. Is that what NativeUI uses?

It doesn't actually matter what I would use because it can't affect anything. I can't measure a string and then say to NativeUI "This string is X units wide, display it all on one line". I could process the string with replacement functions and everything but it would still wrap incorrectly.

Or are you saying that I _can_ override the wrapping functionality of NativeUI to force things to not wrap?

**Comment by Guad** [comment] 2017-09-03 22:34
Currently NativeUI just counts the characters. What I meant is, ideally NativeUI would use that native. I'll get around to it someday

**Comment by LeeC2202** [comment] 2017-09-03 22:39
Ah, right... I understand now.

I only noticed it because I am doing a collaboration with someone using a NativeUI menu system and just thought it was worth mentioning. I'll close this then.

**Comment by Guad** [comment] 2017-09-03 22:40
It's okay, I'll close this when I fix it

**Comment by karimcambridge** [comment] 2019-03-22 09:48
For now, you can use this regex `\~(.*?)\~` to strip the colour codes under the string measurer?

**Comment by justalemon** [comment] 2019-03-22 20:39
If I'm not wrong, we are running the width evaluation every tick. We know that regex is slow so adding it is going to cause performance issues when the menus are open (I guess around a 30%).

**Comment by LeeC2202** [comment] 2019-03-22 20:53
My advice would be to not run width evaluation every tick, on something that only changes width when the content changes. That would also mean the regex would only ever run once when the content changed, which would get you a chunk of performance back.

The less calculating you can do when it only needs to be drawing things, the better it will perform when the menu is open. Might be worth looking into that as an optimisation step perhaps.

**Comment by karimcambridge** [comment] 2019-03-22 20:54
It can be easily changed to only calculate when the text changes.

**Comment by justalemon** [comment] 2019-03-22 22:17
There is also the native mentioned by Guad to measure the width correctly. We need to try that first and then use regex as our last resort.

**Comment by karimcambridge** [comment] 2019-03-22 22:18
I'm just saying if anyone wants a fast fix. Because it seems like Guad is busy anyway noone else seems to be attempting a pull request.

**Comment by justalemon** [comment] 2019-03-23 05:45
Attempted to use the native mentioned by @Guad, because there is not a lot of documentation it appears that I did something wrong.

![image](https://user-images.githubusercontent.com/11861253/54862183-8e62c380-4d15-11e9-8304-7c89f22f8d45.png)

The code is on the [lemon/string-measurement](https://github.com/Guad/NativeUI/tree/lemon/string-measurement) branch.

**Comment by justalemon** [comment] 2019-03-23 05:46
Added the Help Wanted tag because I don't know how to make this work.

**Comment by LeeC2202** [comment] 2019-03-23 12:37
This is actually more tricky than it seems, because you can't just strip out the control codes, you have to remember where they all were, so you can put them back into the adjusted string. I can't do anything directly with the code because I don't use all this git stuff. I'll post what I have written, just in case it will help. This was written in a winforms app but the core code will work.

I have this struct to store the control codes as an index and string value.

`public struct ControlChar
{
	public int Index;
	public string ControlString;

	public ControlChar(int index, string controlString)
	{
		Index = index;
		ControlString = controlString;
	}
}`

Then I first run this code to collect and store those codes... testString would be replaced with your actual string being measured.

`List<ControlChar> ControlCharIndexes = new List<ControlChar>();

// sample string...
string testString = "~y~Hello there ~r~I am some text that is ~g~too long.";

int indexOffset = 0;

for (int x = 0; x < testString.Length; x++)
{
	if (testString.Substring(x, 1) == "~")
	{
		string controlCode = testString.Substring(x, 3); // Get the control code string
		ControlCharIndexes.Add(new ControlChar(x + indexOffset, controlCode)); // Store the control code in the list
		testString = testString.Remove(x, 3); // Remove the code from the string
		indexOffset += 3; // add 3 to the index offset to compensate for the removed string
	}
}`

Then you would do your string measuring and every time you insert a "~n~" to force a newline, you would add 3 to any stored index values **at that position or later**. So if for example you had inserted one at index 21, then you would run this code to add 3 to the indexes of the stored control codes that are currently 21 or higher. insertIndex would be the position you had inserted the "~n~" code

`for (int i = 0; i < ControlCharIndexes.Count; i++)
{
	ControlChar cc = ControlCharIndexes[i];

	if (cc.Index >= insertIndex)
	{
		cc.Index += 3;
		ControlCharIndexes[i] = cc;
	}
}`

Finally, this would add the original control codes back into the string, taking into account the additional "~n~" insertions.

`for (int i = 0; i < ControlCharIndexes.Count; i++)
{
	ControlChar cc = ControlCharIndexes[i];
	testString = testString.Insert(cc.Index,cc.ControlString);
}`

After processing, the original string looks like this "~y~Hello there ~r~I am some~n~ text that is ~g~too long."

If you were to strip out excess spaces, like the one before "text", then you'd have to adjust the indexes to compensate for that as well.

I have a habit of writing code that isn't probably the best way but this might give you some help to solving the problem. Sorry if this causes more confusion that it tries to solve.

**Comment by LeeC2202** [comment] 2019-03-23 12:40
I don't know why the code formatting isn't working properly, I don't think GitHub likes Opera, sorry :(

**Comment by LeeC2202** [comment] 2019-03-23 12:43
Sorry, I deleted the comment I made, the screwed up code formatting just made it a confusing mess. I will try and find another way of posting the code later. :(

**Comment by LeeC2202** [comment] 2019-03-23 13:39
Hmmm, okay... now I am confused. I added some string measuring code to a mod I am writing yesterday and decided to test it with some colour codes.

This:
`"This is some text"`

Returned the exact same length as this:
`"~r~This is ~y~some text"`

![text_measure](https://user-images.githubusercontent.com/13275001/54866844-f397d280-4d70-11e9-91d2-caccb84c57ab.jpg)

This is the code my measure is using.
`
        private static float GetStringWidth(string text, Font font, float scale)
        {
            Function.Call(Hash._SET_TEXT_ENTRY_FOR_WIDTH, "STRING");
            Function.Call((Hash)0x6C188BE134E074AA, text);
            Function.Call(Hash.SET_TEXT_FONT, (int)font);
            Function.Call(Hash.SET_TEXT_SCALE, scale, scale);
            return Function.Call<float>(Hash._GET_TEXT_SCREEN_WIDTH, true);
        }
`

**Comment by karimcambridge** [comment] 2019-03-23 17:09
Hold on, I notice your `getTextScreenWidth` is true?

I use false for some reason... have u tested the difference when its false and true?

```public static MeasureStringWidthNoConvert(input: string) {
		mp.game.ui.setTextEntryForWidth("STRING");
		ResText.AddLongString(input);
		mp.game.ui.setTextFont(0);
		mp.game.ui.setTextScale(0.35 * 1.25, 0.35);
		return mp.game.ui.getTextScreenWidth(false);
	}

	public static MeasureString(str: string) {
		const screenw = Screen.width;
		const screenh = Screen.height;
		const height = 1080.0;
		const ratio = screenw / screenh;
		const width = height * ratio;
		return this.MeasureStringWidthNoConvert(str) * width;
	}```

**Comment by LeeC2202** [comment] 2019-03-23 19:12
Just tested with false and they still both return the same length. So that begs the question, if that measurement code always returns the same length, no matter whether control codes are used or not, where does the problem here come from?

Just noticed, the string measuring code uses different hash values in NativeUI, I wonder if that has anything to do with it?

`	public static float MeasureStringWidthNoConvert(string str, Font font, float scale)
	{
		Function.Call((Hash)0x54CE8AC98E120CAB, "STRING");
		AddLongString(str);
		return Function.Call<float>((Hash)0x85F061DA64ED2F67, (int)font) * scale;
	}
`

**Comment by karimcambridge** [comment] 2019-03-23 19:16
Well AFAIK `0x85F061DA64ED2F67` = `_GET_TEXT_SCREEN_WIDTH` = `_END_TEXT_COMMAND_GET_WIDTH` but I was wondering, why is it passing `font` as an int? and then multiplying it by scale?

**Comment by LeeC2202** [comment] 2019-03-23 19:26
It's so confusing with different native names being used all over the place. Maybe the original parameter was marked as a float, which might have caused the confusion over what it actually requires.

Perhaps this issue doesn't exist anymore though, a lot can happen in 18 months as more is discovered about how the natives are used.

**Comment by LeeC2202** [comment] 2019-03-23 19:46
Just created a quick project and both of them wrap at the same length now, so whatever the problem used to be, it's no longer present. It does seem to wrap a bit early but it's consistent when it wraps, so I would suggest that this issue be finally laid to rest.

Top line has 4 control codes in the description, the bottom line has none,.

![fixed_wrapping](https://user-images.githubusercontent.com/13275001/54870883-46d74880-4da4-11e9-85e0-7afe60ee1283.jpg)

**Comment by karimcambridge** [comment] 2019-03-23 19:48
And this is confirmed using the current version with no modifications?

Did you try different resolutions?

**Comment by LeeC2202** [comment] 2019-03-23 19:53
Just put the old 1.7 dll in and the problem returned, so this is something that is definitely fixed in versions later than 1.7. This is with the old dll.

![old_wrapping](https://user-images.githubusercontent.com/13275001/54870966-52773f00-4da5-11e9-99e2-1fc86546ac65.jpg)

No, didn't try different resolutions, I only run at 1920x1200 and I don't use NativeUI now to be honest.

**Comment by karimcambridge** [comment] 2019-03-23 19:58
Ah, it seems like before .. at 1.7 it still uses the character calculating instead of the game functions.

https://github.com/Guad/NativeUI/commit/8de27741b484d0681c7ef85d3d3b2dd6181281f9

So the game function more or less fixed it.

**Comment by LeeC2202** [comment] 2019-03-23 19:59
Yep, I think this can be closed now.

**Comment by justalemon** [comment] 2019-08-25 22:22
Great news everyone! We now use the native mentioned by @Guad to accurately calculate the number of lines that a specific string uses:

![image](https://user-images.githubusercontent.com/11861253/63656687-4123cb80-c765-11e9-9235-f82e6ead9e9c.png)

**Closed by justalemon** 2019-08-25 22:22 UTC
Labels: bug, help wanted
